### ISSUE TITLE
LoadPlugIn cannot be called while a plug-in is being loaded

### ISSUE THREAD

**Issue by jordillonch** [mcneel/rhino-developer-samples#3]
When I try to test the skin example I get this error:
`LoadPlugIn cannot be called while a plug-in is being loaded`
I'm using Rhinoceros 5 (64 bits)

**Comment by dalefugier** [comment]
@jordillonch, which Skin sample are you testing? C++ or C#?

**Comment by jordillonch** [comment]
C#, sorry.

**Comment by dalefugier** [comment]
@jordillonch, I am not able to reproduce this. This is a message displayed by Rhino's plug-in manager and has nothing to do with using a Skin assembly. Are you also loading a custom plug-in?

**Comment by jordillonch** [comment]
Yes, I have a custom plugin, too. 
I found that I can not reproduce in other computer.
Thanks for your time 🙂
