### ISSUE TITLE
Unable to load RhinoLibrary dll while running HelloWorld sample

### ISSUE THREAD

**Issue by Jackarnd** [mcneel/rhino-developer-samples#41]
Hello ! I tried to run the hello world example in C# but I get an error at this line `using (new RhinoCore(args))` :
`System.DllNotFoundException : 'unable to load 'RhinoLibrary' DLL: The specified module cannot be found. (HRESULT exception : 0x8007007E)'`

I re-referenced `RhinoCommon` and `Rhino.Inside` from the NuGet packages just to be sure. But I still get the issue...

Am I missing a setting step?

**Comment by sbaer** [comment]
Do you have Rhino 7 installed on your computer?

**Comment by Jackarnd** [comment]
I'm on rhino 6. I need to have specifically rhino 7?

**Comment by sbaer** [comment]
Yes, Rhino.Inside is new to Rhino 7 and you have to have Rhino 7 installed for it to work.
