### ISSUE TITLE
ResetBlock.rvb throws 'undefined variable' error

### ISSUE THREAD

**Issue by ianisl** [mcneel/rhino-developer-samples#47]
The script ResetBlock.rvb throws an 'undefined variable: arrXform' error.
This can be fixed by adding `arrXform` to the `Dim` declarations on line 17, since the script uses `Option Explicit`:
`Dim arrBlocks, strBlock, arrPoint, arrVector, arrXform`

**Comment by dalefugier** [comment]
Thanks
