### ISSUE TITLE
C++ export and import data

### ISSUE THREAD

**Issue by gedw99** [mcneel/rhino-developer-samples#6]
I am writing a utility to operate on rhino files so I can export the mesh data.
Is that supported on your api ? Not sure if you provide file level api you see ..

Next I want to write a plug-in to pull and push data via the rhino program itself. The idea is to update the mesh as the architect works. I assume that I need some sort of developer account to allow my colleagues to use that ?

**Comment by dalefugier** [comment]
Hi @gedw99,

It is possible to export mesh data from the Rhino C++ SDK and RhinoCommon (toolkits to build plug-ins for Rhino) and from openNURBS (a toolkit to read and write 3dm files).

I don't quite understand your second question. We'll probably need more information on what you are trying to do and why before we can answer this.

In the future, you might consider asking your questions on our developer forum, as you usually get a quicker reply here.

https://discourse.mcneel.com/

-- Dale

**Comment by gedw99** [comment]
@dalefugier 

Hey, thanks for the quick response. 
Its easier to ask here because i am a programmer and use github for most things. Hope you dont mind.

1. Great. i found the c++ code.  Looks like great code. I will likly use SWIG to interoperate with it.

2. Regarding interacting with the actual GUI Rhino software of your company.  My use case is that i need to work with the mesh data in another program ( in my case 3d printing ), edit it, and then see it updated inside your Rhino GUI. Thats what i meant about push and pull data.   My software can write out the rhino file, but thats not optimal, because your software has a lock on the file. Instead its better to have some sort of socket connection between my software and yours.  Normally software provides some sort of event, signal, change feed to do this.

Regards

Ged
