### ISSUE TITLE
FileObjWriteOptions property setting seems not working

### ISSUE THREAD

**Issue by haheehong1** [mcneel/rhino-developer-samples#64]
https://github.com/mcneel/rhino-developer-samples/blob/3179a8386a64602ee670cc832c77c561d1b0944b/rhino.inside/dotnet/SampleConvert/Program.cs#L55

Hello, 
I'm testing this FileObj.Write method with this options setting from this reference.
However, it seems it's not working. 
the yz is not flipped and the material is not written.

Could you help me solving this issue?

**Comment by dalefugier** [comment]
Seems to work here with the current Rhino 7, which is SR18. What version of Rhino 7 do  you have?

**Comment by haheehong1** [comment]
Hello, dalefugier.
Thank you for answering 👍 
I updated my rhino and package to 7.18.
Still the FileObj.Write options are not working.

I'm actually not running the sample code, but using part of the code and making a new gh component.
Like this.
https://github.com/haheehong1/ObjExport/blob/b97e57c859472b5473dc2a5ca06d9117cc5d66dc/objexporttest/objexporttestComponent.cs

With this code, I can write obj file but still the options (map y to z, export material..) are not working.
Do you know what should I chang to make this work?

**Comment by dalefugier** [comment]
Materials are not stored on the mesh geometry but, rather, the Rhino mesh objects. Thus, calling `FileObj.Write` and passing an array of mesh geometry will never produce `mtl` files.
