### ISSUE TITLE
How to add command for SampleMeshExport

### ISSUE THREAD

**Issue by GeoGroup** [mcneel/rhino-developer-samples#76]
I am a beginer of Rhino developer and have successfully complied the SampleExportMesh. I want to known how to add a command to call the function to export a mesh to a file?

**Comment by dalefugier** [comment]
Hi @GeoGroup,

For quicker response, please direct your questions to Discourse.

https://discourse.mcneel.com/

The [SampleExportMesh](https://github.com/mcneel/rhino-developer-samples/tree/7/cpp/SampleExportMesh) project build a Rhino file export plug-in. So if build and load the project and load the plug-in in Rhino, you'll see `Sample Mesh` file type when saving a file.

**Comment by GeoGroup** [comment]
Thanks for your repley. I have already get the "SampleExportMesh.rhp" file and zip it into a .rhi file. After installing the plug-in. I don not know how to run the plug-in.  I will  direct my questions to Discourse. Many thanks.
