### ISSUE TITLE
error, 3dm file was created by Rhino 8. This model cannot be read by Rhino 7.

### ISSUE THREAD

**Issue by hopezh** [mcneel/rhino-developer-samples#95]
I got the following error while trying to open the `circle.3dm` file generated by the example script [SampleCreateCircleAndWriteTo3dmFile.py](https://github.com/mcneel/rhino-developer-samples/blob/7/rhino3dm/py/SampleCreateCircleAndWriteTo3dmFile.py) in Rhino7.

I'd like to ask how to **write 3dm file using rhino3dm that is compatible with Rhino7**. 

![2024-05-05 21 29 48](https://github.com/mcneel/rhino-developer-samples/assets/23435810/33f67dbf-3b2c-4036-8813-a37bf2818d0b)

**Comment by dalefugier** [comment]
```
model.Write("circle.3dm", 70)
```
